use movies;

SELECT ST.NAME, SI.STARNAME
FROM STUDIO ST
FUll JOIN MOVIE M ON ST.NAME = M.STUDIONAME 
FULL JOIN STARSIN SI ON M.TITLE = SI.MOVIETITLE AND M.YEAR = SI.MOVIEYEAR
ORDER BY ST.NAME;

SELECT ME.NAME
FROM MOVIEEXEC ME
JOIN MOVIE MV ON MV.PRODUCERC# = ME.CERT#
JOIN STARSIN SI ON MV.TITLE = SI.MOVIETITLE AND MV.YEAR = SI.MOVIEYEAR
WHERE SI.STARNAME = 'Harrison Ford';

SELECT MS.NAME
FROM MOVIESTAR MS
JOIN STARSIN SI ON MS.NAME = SI.STARNAME
JOIN MOVIE MV ON MV.TITLE = SI.MOVIETITLE AND MV.YEAR = SI.MOVIEYEAR
WHERE MV.STUDIONAME = 'MGM';

SELECT EX.NAME, M.TITLE 
FROM MOVIEEXEC EX
JOIN MOVIE M ON M.PRODUCERC# = EX.CERT#
WHERE EX.NAME IN 
			(
			  SELECT EX1.NAME
			  FROM MOVIEEXEC EX1
			  JOIN MOVIE M1 ON M1.PRODUCERC# = EX1.CERT#
			  WHERE M1.TITLE = 'Star Wars');


SELECT M.TITLE, M.YEAR, EX.NAME
FROM MOVIE M
LEFT JOIN MOVIEEXEC EX ON EX.CERT# = M.PRODUCERC#;


--Напишете заявка, която извежда заглавието,
--годината, името на продуцента, името на студиото
--и адреса на студиото на всеки филм. Да се включат
--и филмите, за които продуцентът и/или студиото е
--неизвестно.

SELECT M.TITLE, M.YEAR, EX.NAME, S.NAME, S.ADDRESS 
FROM MOVIE M
LEFT JOIN STUDIO S ON M.STUDIONAME = S.NAME
LEFT JOIN MOVIEEXEC EX ON EX.CERT# = M.PRODUCERC#;
            

SELECT MS.NAME
FROM MOVIESTAR MS
LEFT JOIN STARSIN SI ON MS.NAME = SI.STARNAME
WHERE SI.MOVIETITLE IS NULL;


