use pc;

--ZAD 1
SELECT model, speed AS MHz, hd AS GB
FROM pc
WHERE price < 1200	;

--ZAD 2
SELECT model, price / 1.10 AS EURO
FROM laptop
ORDER BY PRICE;

--ZAD 3
SELECT MODEL, HD AS GB , SCREEN AS INC
FROM LAPTOP
WHERE price > 1000;

--ZAD 4
SELECT *
FROM PRINTER
WHERE COLOR = 'Y';

--ZAD 5
SELECT MODEL, HD, CD
FROM PC
WHERE (CD = '12x' OR CD = '16x') AND PRICE < 2000; 

-- ZAD 6
SELECT CODE, MODEL, SPEED + RAM + 10*SCREEN AS RATING
FROM LAPTOP
ORDER BY RATING DESC;